apiVersion: v1
kind: Service
metadata:
  name: otus-hw-svc
  namespace: otus-hw
spec:
  selector:
    app: otus-hw
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer