apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  otus-hw-ingress
  namespace: otus-hw
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2/
    kubernetes.io/ingress.class: "nginx"
spec:

  rules:
  - host: arch.homework
    http:
      paths:
      # - path: /health
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: otus-hw-svc
      #       port:
      #         number: 80
      - path: /()(health)
        pathType: ImplementationSpecific
        backend:
          service:
            name: otus-hw-svc
            port:
              number: 80
      - path: /otusapp/(.*)/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: otus-hw-svc
            port: 
              number: 80
